### ISSUE TITLE
Join forces with https://github.com/websideproject/paddle-billing-client

### ISSUE THREAD

**Issue by ddorian** [Invincibear/paddle-billing-python-sdk#1]
Have you seen https://github.com/websideproject/paddle-billing-client ? Maybe join forces there?

**Comment by Invincibear** [comment]
I wish I had, I probably wouldn't've made this! I made it out of necessity to get my SaaS integrated with the new Paddle Billing because I couldn't find a Python library, I thought it was too new and didn't exist, I guess I didn't look hard enough...

The two Python clients are fundamentally different though, looks like `paddle-billing-client` made everything its own way from scratch, whereas `paddle-billing-python-sdk` is a python-translated version of the official `paddle-php-sdk`. 

`paddle-billing-python-sdk` is fully operational, only in alpha status because `paddle-php-sdk` still hasn't hit version `1.0`, otherwise it has the same capabilities as its PHP counterpart. `paddle-billing-python-sdk` and `paddle-php-sdk` follow the same naming conventions whenever possible, has full API coverage, and full test coverage.

**Comment by ddorian** [comment]
> whereas paddle-billing-python-sdk is a python-translated version of the official paddle-php-sdk

Is this auto translation?

**Comment by Invincibear** [comment]
> > whereas paddle-billing-python-sdk is a python-translated version of the official paddle-php-sdk
> 
> Is this auto translation?

I wish lol. It took ~2 weeks of full-time work, another week of cleanup and testing, and now maintenance every few days of minutes to hours, depending how big of a change is made.
